export const userTypes = {
    FETCH_ALL_HOTELS: 'FETCH_ALL_HOTELS', // admin also have this one
};

export const filterTypes = {
    APPLY_SUGGESTION: 'APPLY_SUGGESTION',
    APPLY_DATES: 'APPLY_DATES',
    APPLY_GUESTS: ' APPLY_GUESTS',
};

export const autosuggestTypes = {
    UPDATE_INPUT_VALUE: 'UPDATE_INPUT_VALUE',
    CLEAR_SUGGESTIONS: 'CLEAR_SUGGESTIONS',
    MAYBE_UPDATE_SUGGESTIONS: 'MAYBE_UPDATE_SUGGESTIONS',
    LOAD_SUGGESTIONS_BEGIN: 'LOAD_SUGGESTIONS_BEGIN',
};
