export const FETCH_ALL_HOTELS = 'FETCH_ALL_HOTELS';

export const UPDATE_INPUT_VALUE = 'UPDATE_INPUT_VALUE';
export const CLEAR_SUGGESTIONS = 'CLEAR_SUGGESTIONS';
export const CLEAR_VALUE = 'CLEAR_VALUE';
export const MAYBE_UPDATE_SUGGESTIONS = 'MAYBE_UPDATE_SUGGESTIONS';
export const LOAD_SUGGESTIONS_BEGIN = 'LOAD_SUGGESTIONS_BEGIN';

export const SET_DATE_RANGE = 'SET_DATE_RANGE';
export const INCREMENT_GUEST_COUNT = 'INCREMENT_GUEST_COUNT';
export const DECREMENT_GUEST_COUNT = 'DECREMENT_GUEST_COUNT';
export const SET_LOCATION = 'SET_LOCATION';
export const CLEAR_DATE_FILTER = 'CLEAR_DATE_FILTER';
export const CLEAR_GUEST_FILTER = 'CLEAR_GUEST_FILTER';
export const CLEAR_LOCATION_FILTER = 'CLEAR_LOCATION_FILTER';

// not used yet
export const APPLY_SUGGESTION = 'APPLY_SUGGESTION';
export const APPLY_DATES = 'APPLY_DATES';
export const APPLY_GUESTS = ' APPLY_GUESTS';

export const FETCH_USER_BOOKINGS = 'FETCH_USER_BOOKINGS';

export const SET_BOOKING_LOCATION = 'SET_BOOKING_LOCATION';
export const CLEAR_BOOKING_LOCATION_FILTER = 'CLEAR_BOOKING_LOCATION_FILTER';
export const SWITCH_BOOKING_RELEVANCE = 'SWITCH_BOOKING_RELEVANCE';
