export const HIDE_BOOKING_MODAL = 'HIDE_BOOKING_MODAL';
export const SHOW_BOOKING_MODAL = 'SHOW_BOOKING_MODAL';
export const FETCH_HOTEL = 'FETCH_HOTEL';
export const FETCH_OCCUPIED_DATES = 'FETCH_OCCUPIED_DATES';
