export const CREATE_USER = 'CREATE_USER';
export const VALIDATE_USER = 'VALIDATE_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

export const HIDE_AUTH_MODAL = 'HIDE_AUTH_MODAL';
export const SHOW_AUTH_MODAL = 'SHOW_AUTH_MODAL';
