export const userTypes = {
    CREATE_USER: 'CREATE_USER',
    VALIDATE_USER: 'VALIDATE_USER',
    LOGOUT_USER: 'LOGOUT_USER',
    VALIDATE_USER_SUCCESSED: 'VALIDATE_USER_SUCCESSED', // not used
    VALIDATE_USER_FAILED: 'VALIDATE_USER_FAILED', // not used
};

export const modalTypes = {
    SWITCH_MODAL_INNER: 'SWITCH_MODAL_INNER',
    HIDE_MODAL: 'HIDE_MODAL',
    SHOW_MODAL: 'SHOW_MODAL',
    SHOW_SIGNUP_MODAL: 'SHOW_SIGNUP_MODAL',
    SHOW_LOGIN_MODAL: 'SHOW_LOGIN_MODAL',
};
